import fs from 'fs';

let en = JSON.parse(fs.readFileSync('locales/en.json', 'utf-8'));
let pt = JSON.parse(fs.readFileSync('locales/pt.json', 'utf-8'));

if (!en.pools) en.pools = {};
if (!pt.pools) pt.pools = {};

en.pools.successSwap = "Transaction sent successfully! Updating balances...";
pt.pools.successSwap = "Transação enviada com sucesso! Atualizando saldos...";

en.pools.loginToAdd = "Please login to add liquidity.";
pt.pools.loginToAdd = "Por favor, faça login para adicionar liquidez.";

en.pools.errorAdd = "Error adding liquidity: ";
pt.pools.errorAdd = "Erro ao adicionar liquidez: ";

en.pools.loginToRemove = "Please login to remove liquidity.";
pt.pools.loginToRemove = "Por favor, faça login para remover liquidez.";

en.pools.errorRemove = "Error removing liquidity: ";
pt.pools.errorRemove = "Erro ao remover liquidez: ";

en.pools.insufficientBalanceExt = "Insufficient balance of {token}. You have {balance}.";
pt.pools.insufficientBalanceExt = "Saldo insuficiente de {token}. Você possui {balance}.";

en.pools.yourShareText = "Your share: ";
pt.pools.yourShareText = "Sua fatia: ";

en.pools.myLiquidity = "My Liquidity";
pt.pools.myLiquidity = "Minha Liquidez";

en.pools.slippage = "Slippage Tolerance";
pt.pools.slippage = "Tolerância de Deslizamento";

en.pools.disclaimer = "*Operation performed on Hive Engine via Keychain. Make sure to sign with your active key.";
pt.pools.disclaimer = "*Operação realizada na Hive Engine via Keychain. Certifique-se de assinar com sua chave ativa.";

en.pools.addLiquidityInfo = "By providing liquidity, you must add both pool assets in the correct market proportion. In return, you receive participation tokens (Shares) that represent your share in the pool and earn fees generated by traders.";
pt.pools.addLiquidityInfo = "Ao prover liquidez, você deve adicionar os dois ativos da pool na proporção correta de mercado. Em troca, você recebe tokens de participação (Shares) que representam sua parcela na pool e ganha taxas geradas por traders.";

en.pools.reserveOf = "Reserve of";
pt.pools.reserveOf = "Reserva de";

en.pools.priceIndicators = "Price Indicators";
pt.pools.priceIndicators = "Indicadores de Preço";

en.pools.additionalInfo = "Additional Information";
pt.pools.additionalInfo = "Informações Adicionais";

en.pools.totalSharesInfo = "Total Shares (Pool Shares)";
pt.pools.totalSharesInfo = "Total de Quotas (Pool Shares)";

en.pools.liquidityProviders = "Liquidity Providers";
pt.pools.liquidityProviders = "Provedores de Liquidez";

en.pools.showingAllProviders = "Showing all {count} providers of this pool.";
pt.pools.showingAllProviders = "Mostrando todos os {count} provedores desta pool.";

en.pools.removePercent = "Remove {percent}% Liquidity";
pt.pools.removePercent = "Remover {percent}% de Liquidez";

en.pools.balance = "Balance:";
pt.pools.balance = "Saldo:";

en.pools.refreshBalances = "Refresh Balances";
pt.pools.refreshBalances = "Atualizar Saldos";

fs.writeFileSync('locales/en.json', JSON.stringify(en, null, 2));
fs.writeFileSync('locales/pt.json', JSON.stringify(pt, null, 2));
